### ISSUE TITLE
Ignore-Important-Errors Flag Failing and asking to use Ignore-Important-Errors

### ISSUE THREAD

**Issue by magicaldave** [alvazir/habasi#2]
Hello! We've recently started using Habasi on the momw-patches repository in order to compile a merged version of the patches we host there. This worked great for a while. However, last night, we started getting unexpected failures.

The problem: DeltaPlugin serializes XSCL at the end of a FRMR. According to the spec XSCL should come after the ID. This causes Habasi to fail. 

We *were* using --ignore-important-errors to bypass this and merge together those plugins which weren't affected by this. That just *stopped* working as of our last job.

Would it be possible to make habasi do this in a fashion that doesn't rely so strictly on the ordering of subrecords?

This is really two separate problems, as --ignore-important-errors seems to just not do anything at all now. Here's the job logs:

```
Log is being written into "/usr/bin/habasi.log"
Global list options: mode = keep, config = openmw.cfg, ignore_important_errors
Gathering plugins from game configuration file "openmw.cfg"
Plugin list was expanded with contents of load order due to "use_load_order" flag
Processing list "MergedLoadOrder.esp" with options: mode = complete_replace, config = openmw.cfg, use_load_order, strip_masters, exclude_deleted_records, ignore_important_errors
  Processing plugin "/builds/modding-openmw/momw-patches/01 BCOM+Imperial Towns Revamp Patch/BCOM+Imperial Towns Revamp Patch.esp"
Output plugin "MergedLoadOrder.esp": masters will not be stripped due to encountering external reference
  Processing plugin "/builds/modding-openmw/momw-patches/02 UvirithsLegacy+TR Patch/UvirithsLegacy+TR Patch.esp"
Failed to process list "MergedLoadOrder.esp, no_dry_run, use_load_order, exclude_deleted_records, complete_replace, strip_masters, ignore_errors, no_insufficient_merge"
Caused by:
    Failed to process plugin
    Failed to load plugin "/builds/modding-openmw/momw-patches/02 UvirithsLegacy+TR Patch/UvirithsLegacy+TR Patch.esp": Unexpected Tag: CELL::XSCL
    Use --ignore-important-errors to ignore
    Consider reporting the error to add this tag to the list of unexpected tags to skip by default
```

Failed Job: https://gitlab.com/modding-openmw/momw-patches/-/jobs/5617347498

Successful one: https://gitlab.com/modding-openmw/momw-patches/-/jobs/5570279215

I believe the failure of --ignore-important-plugins is a regression introduced by f74a5b5.

**Comment by magicaldave** [comment]
Update: the failure is now fixed in DP, but I think --ignore-important-errors is still not working.

**Comment by alvazir** [comment]
Hello! Thank you for such a great issue description. 

1. It's good that CELL::XSCL problem is gone. Though I've added the "workaround" just in case someone uses older DP versions [src/config/settings.rs](https://github.com/alvazir/habasi/commit/9fad5c65c6530d8ca407deb60d425197d0416c69#diff-d572ad1b7153cbdba3cde3e371ecfa12b90d84f7a243edc9cec3bf47fe7ed086)
2. Fixed --ignore-important-errors to work with unexpected tags [src/main.rs](https://github.com/alvazir/habasi/commit/7d759d42f5e09e4efd947da77196b6f89f9c6182). It was a regression from that commit as you suspected. Actually it was semi-intentional. I haven't expected OpenMW to advance so fast. Just had a desire to adapt ASAP when the issue returns with new fields in months or years :-)

Please check that updated program works as expected for you.

**Comment by magicaldave** [comment]
All seems well here now. :+1:
